spring:
  datasource:
    url: jdbc:h2:mem:aiprojectmanager;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  jwt:
    secret: verysecretkeyverysecretkeyverysecretkey12345
    expiration-ms: 86400000
  meeting:
    google:
      api-key: ${GOOGLE_MEET_API_KEY:}
      oauth-token: ${GOOGLE_MEET_OAUTH_TOKEN:}
      calendar-id: ${GOOGLE_MEET_CALENDAR_ID:primary}
